# Generated by Django 3.1.5 on 2022-02-01 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('post', models.TextField()),
                ('cover', models.ImageField(upload_to='post_covers')),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
